name: VPNRenderTest
options:
  bundleIdPrefix: me.spideywv
  deploymentTarget:
    iOS: "16.0"

targets:
  VPNRenderTest:
    type: application
    platform: iOS
    sources:
      - path: VPNTest
    dependencies:
      - target: VPNRenderExtension
    entitlements:
      path: VPNTest/VPNRenderTest.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.spideywv.vpnrendertest
        DEVELOPMENT_TEAM: 7S264298H8
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_UIRequiresFullScreen: NO
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
    info:
      path: VPNTest/Info.plist
      properties:
        CFBundleDisplayName: VPN Render Test
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSLocalNetworkUsageDescription: "Used to test the virtual VPN network."

  VPNRenderExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: GeneralsVPN/PacketTunnelProvider.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "$(GX_BUNDLE_ID).VPNRenderExtension"
        DEVELOPMENT_TEAM: 7S264298H8
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        APPLICATION_EXTENSION_API_ONLY: YES
    info:
      path: GeneralsVPN/Info.plist
    entitlements:
      path: GeneralsVPN/GeneralsVPN.entitlements
